#include "code_generator.h"

#include <iostream>
#include <fstream>
#include <map>
#include <string>

using namespace std;



// Escape Python string quotes

string escapeQuotes(string s)
{
    string result;


    for(char c : s)
    {
        if(c == '"')
            result += "\\\"";
        else if(c == '\\')
            result += "\\\\";
        else
            result += c;
    }


    return result;
}






CodeGenerator::CodeGenerator(
    const vector<Instruction>& code
)
    : instructions(code)
{
}







void CodeGenerator::generatePython() const
{

    ofstream out("output.py");


    if(!out.is_open())
    {
        cout
        << "ERROR: output.py create kora jayni.\n";

        return;
    }





    // Label position

    map<string,int> labelPosition;


    for(size_t i=0;i<instructions.size();i++)
    {

        if(instructions[i].op=="LABEL")
        {
            labelPosition[
                instructions[i].result
            ] = i;
        }

    }





    out
    << "# Auto-generated by Borno Compiler\n\n";



    out
    << "memory = {}\n\n";





    // Value getter


    out
    << "def get_value(x):\n";


    out
    << "    if x.startswith('\"') and x.endswith('\"'):\n";

    out
    << "        return x[1:-1]\n\n";


    out
    << "    try:\n";

    out
    << "        if '.' in x:\n";

    out
    << "            return float(x)\n";

    out
    << "        return int(x)\n";

    out
    << "    except ValueError:\n";

    out
    << "        return memory.get(x,0)\n\n";





    out
    << "pc = 0\n\n";


    out
    << "while pc < "
    << instructions.size()
    << ":\n";







    for(size_t i=0;i<instructions.size();i++)
    {


        const Instruction& ins =
            instructions[i];



        if(i==0)
            out<<"    if pc == "<<i<<":\n";
        else
            out<<"    elif pc == "<<i<<":\n";







        // Assignment


        if(ins.op=="=")
        {

            out
            << "        memory[\""
            << escapeQuotes(ins.result)
            << "\"] = get_value(\""
            << escapeQuotes(ins.arg1)
            << "\")\n";


            out
            << "        pc += 1\n";

        }







        // Arithmetic


        else if(
            ins.op=="+" ||
            ins.op=="-" ||
            ins.op=="*" ||
            ins.op=="/"
        )
        {


            if(ins.op=="/")
            {

                out
                << "        if get_value(\""
                << escapeQuotes(ins.arg2)
                << "\") == 0:\n";


                out
                << "            raise RuntimeError(\"Division by zero\")\n";

            }



            out
            << "        memory[\""
            << escapeQuotes(ins.result)
            << "\"] = get_value(\""
            << escapeQuotes(ins.arg1)
            << "\") "
            << ins.op
            << " get_value(\""
            << escapeQuotes(ins.arg2)
            << "\")\n";



            out
            << "        pc += 1\n";

        }








        // Comparison


        else if(
            ins.op==">" ||
            ins.op=="<" ||
            ins.op=="=="
        )
        {

            out
            << "        memory[\""
            << escapeQuotes(ins.result)
            << "\"] = get_value(\""
            << escapeQuotes(ins.arg1)
            << "\") "
            << ins.op
            << " get_value(\""
            << escapeQuotes(ins.arg2)
            << "\")\n";


            out
            << "        pc += 1\n";

        }







        // PRINT


        else if(ins.op=="PRINT")
        {


            out
            << "        print(get_value(\""
            << escapeQuotes(ins.arg1)
            << "\"))\n";


            out
            << "        pc += 1\n";

        }

        else if(ins.op=="LABEL")
        {

            out
            << "        pc += 1\n";

        }








        // GOTO


        else if(ins.op=="GOTO")
        {

            auto it =
            labelPosition.find(
                ins.result
            );


            if(it!=labelPosition.end())
            {

                out
                << "        pc = "
                << it->second
                << "\n";

            }

            else
            {

                out
                << "        raise RuntimeError(\"Unknown label\")\n";

            }

        }








        // IF FALSE


        else if(ins.op=="IF_FALSE")
        {

            auto it =
            labelPosition.find(
                ins.result
            );


            if(it!=labelPosition.end())
            {


                out
                << "        if not get_value(\""
                << escapeQuotes(ins.arg1)
                << "\"):\n";


                out
                << "            pc = "
                << it->second
                << "\n";


                out
                << "        else:\n";


                out
                << "            pc += 1\n";

            }

        }





        else
        {

            out
            << "        raise RuntimeError(\"Unknown instruction\")\n";

        }


    }





    out
    << "    else:\n";

    out
    << "        break\n";



    out.close();



    cout
    << "\n========== CODE GENERATOR ==========\n";


    cout
    << "Executable Python file generated successfully.\n";


    cout
    << "File: output.py\n";

}